# Generated by Django 3.2 on 2023-06-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_profile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='address_detail',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address_Detail'),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='zip_code',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='Zip Code'),
        ),
    ]
