# Generated by Django 3.2 on 2023-06-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20230609_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
