# Generated by Django 3.2 on 2023-06-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client/profile/', verbose_name='Image'),
        ),
    ]
