# Generated by Django 3.2 on 2023-06-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_profile',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'انتي')], max_length=10, verbose_name='Gender'),
        ),
    ]
