# Generated by Django 3.2 on 2023-06-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_profile',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
    ]
