# Generated by Django 3.2 on 2023-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_profile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='address_detail',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='تفاصيل العنوان'),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='blood_group',
            field=models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-'), ('O+', 'O+')], max_length=5, verbose_name='فصيله الدم '),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'انتي')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client/profile/', verbose_name='الصوره الشخصيه'),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='number_phone',
            field=models.CharField(max_length=11, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='الاسم التعريفي'),
        ),
    ]
