# Generated by Django 5.1.4 on 2025-05-16 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20230624_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('treatment', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='client_profile',
            options={'verbose_name': 'Client Profile', 'verbose_name_plural': 'Client Profiles'},
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='blood_group',
            field=models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-'), ('O+', 'O+')], max_length=5, verbose_name='فصيله الدم'),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'انثى')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='الاسم التعريفي'),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip Code'),
        ),
        migrations.CreateModel(
            name='PatientAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_report', models.FileField(upload_to='medical_reports/')),
                ('facial_analysis_image', models.ImageField(blank=True, null=True, upload_to='facial_analysis/')),
                ('is_healthy', models.BooleanField(default=False)),
                ('analysis_results', models.JSONField(default=dict)),
                ('recommendations', models.TextField()),
                ('conditions', models.ManyToManyField(blank=True, to='client.medicalcondition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client_profile')),
            ],
        ),
    ]
