# Generated by Django 5.1.4 on 2025-05-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_medicalcondition_alter_client_profile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientanalysis',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='patientanalysis',
            name='patient',
        ),
        migrations.DeleteModel(
            name='MedicalCondition',
        ),
        migrations.DeleteModel(
            name='PatientAnalysis',
        ),
    ]
