# Generated by Django 5.1.4 on 2025-05-16 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_remove_patientanalysis_conditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('treatment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_report', models.FileField(upload_to='medical_reports/')),
                ('facial_analysis_image', models.ImageField(blank=True, null=True, upload_to='facial_analysis/')),
                ('is_healthy', models.BooleanField(default=False)),
                ('analysis_results', models.JSONField(default=dict)),
                ('recommendations', models.TextField()),
                ('conditions', models.ManyToManyField(blank=True, to='client.medicalcondition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client_profile')),
            ],
        ),
    ]
