"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ioz(2$67#4#4c-eco*w7(^!=18)4o0^79c=--11z2q)cm4px&='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'doctor',                 #!!!!
    'client',                 #!!!!
    
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    "bootstrap4",
    "crispy_forms",
    "crispy_bootstrap4",
    
    "taggit",
    'django_filters',
    
    

    'settings',         #myapp
    
    
    'social_django',     #FACEBOOK
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    
    'social_django.middleware.SocialAuthExceptionMiddleware',   #FACEBOOK
]

ROOT_URLCONF = 'project.urls'


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                
                'social_django.context_processors.backends',             #FACEBOOK
                'social_django.context_processors.login_redirect',       #FACEBOOK
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'
ASGI_APPLICATION = 'project.asgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

""" DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
} """

import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'     
STATICFILES_DIRS = [    
    BASE_DIR / "static" 
]  

MEDIA_URL = '/media/'   
MEDIA_ROOT = BASE_DIR /   'media/' 
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



TAGGIT_CASE_INSENSITIVE = True                  #######



LOGIN_URL = 'login'                      #######
LOGOUT_URL = 'logout'                           #######
LOGIN_REDIRECT_URL = 'doctor:doctors_list'      #######




AUTHENTICATION_BACKENDS = (                               #FACEBOOK
    'social_core.backends.facebook.FacebookOAuth2',       #FACEBOOK
    'social_core.backends.twitter.TwitterOAuth',          #FACEBOOK
    'social_core.backends.github.GithubOAuth2',           #FACEBOOK
    'django.contrib.auth.backends.ModelBackend',          #FACEBOOK
)


SOCIAL_AUTH_FACEBOOK_KEY = '1716371672167554'  # App ID   #FACEBOOK
SOCIAL_AUTH_FACEBOOK_SECRET = '94238b0fdd3dec057fd8a36823d52d75'  # App Secret    #FACEBOOK