# Generated by Django 3.2 on 2023-06-04 02:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitle')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('address_detail', models.CharField(max_length=500, verbose_name='Address_Detail')),
                ('number_phone', models.CharField(max_length=11, verbose_name='Number')),
                ('working_hours', models.IntegerField(blank=True, null=True, verbose_name='Working_Hours')),
                ('waiting_time', models.IntegerField(blank=True, null=True, verbose_name='Waiting_Time')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='Gender')),
                ('who_i', models.CharField(blank=True, max_length=250, null=True, verbose_name='Who_i')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Image')),
                ('specialist_doctor', models.CharField(blank=True, max_length=150, null=True, verbose_name='specialist_doctor')),
                ('fb_link', models.URLField(blank=True, max_length=250, null=True, verbose_name='Facebook')),
                ('twit_link', models.URLField(blank=True, null=True, verbose_name='Twitter_link')),
                ('google_link', models.URLField(blank=True, null=True, verbose_name='Google_link')),
                ('join_us', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Join_Us')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='specialization_image/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
            },
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Rate')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create at')),
                ('review', models.CharField(max_length=500, verbose_name='Review')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profile_review', to='doctor.doc_profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DoctorReview',
                'verbose_name_plural': 'DoctorReviews',
            },
        ),
        migrations.CreateModel(
            name='Doctor_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_doctor/', verbose_name='Image')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_doctor', to='doctor.doc_profile')),
            ],
            options={
                'verbose_name': 'Doctor_Image',
                'verbose_name_plural': 'Doctor_Images',
            },
        ),
        migrations.AddField(
            model_name='doc_profile',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_specialization', to='doctor.specialization'),
        ),
        migrations.AddField(
            model_name='doc_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
