# Generated by Django 3.2 on 2023-06-04 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc_profile',
            options={'verbose_name': 'Doc_Profile', 'verbose_name_plural': 'Doc_Profiles'},
        ),
    ]
