# Generated by Django 3.2 on 2023-06-04 03:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0003_auto_20230604_0547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileDoctor',
        ),
    ]
