# Generated by Django 3.2 on 2023-06-04 04:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0004_rename_profile_profiledoctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileDoctor',
            new_name='Profile_Doctor',
        ),
    ]
