# Generated by Django 3.2 on 2023-06-04 05:21

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('doctor', '0005_rename_profiledoctor_profile_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile_doctor',
            options={'verbose_name': 'Profile_Doctor', 'verbose_name_plural': 'Profile_Doctors'},
        ),
        migrations.AddField(
            model_name='profile_doctor',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
