# Generated by Django 3.2 on 2023-06-09 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_profile_image'),
        ('doctor', '0008_auto_20230609_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('cancelled', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled', to='client.client_profile')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.profile_doctor')),
                ('taken', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken', to='client.client_profile')),
            ],
        ),
    ]
