# Generated by Django 3.2 on 2023-06-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_doctor',
            name='Syndicate',
            field=models.CharField(default=1, max_length=50, verbose_name='Syndicate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_doctor',
            name='active_doctor',
            field=models.BooleanField(default=False, verbose_name='active_doctor'),
        ),
    ]
