# Generated by Django 3.2 on 2023-06-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_profile_image'),
        ('doctor', '0010_auto_20230618_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='taken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_client', to='client.client_profile'),
        ),
    ]
