# Generated by Django 3.2 on 2023-06-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_alter_schedule_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_doctor',
            name='address_detail',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address_Detail'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='number_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitle'),
        ),
    ]
