# Generated by Django 3.2 on 2023-06-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_auto_20230621_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_doctor',
            name='Syndicate',
            field=models.CharField(max_length=50, verbose_name='رقم التسجيل في النقابه'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='address_detail',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='العنوان بالتفصيل'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='google_link',
            field=models.URLField(blank=True, null=True, verbose_name='Googlek'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/profile/', verbose_name='الصوره'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم رباعي'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='number_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الكشف'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='الاسم التعريفي'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='specialist_doctor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف مختصر'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='twit_link',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='waiting_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='وقت الانتظار'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='who_i',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='من انا'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='working_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='ساعات العمل'),
        ),
    ]
