# Generated by Django 3.2 on 2023-06-24 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_auto_20230624_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_doctor',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_specialization', to='doctor.specialization', verbose_name='متخصص في'),
        ),
    ]
