# Generated by Django 3.2 on 2023-06-24 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_alter_profile_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_doctor',
            name='specialist_doctor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='متخصص في'),
        ),
        migrations.AlterField(
            model_name='profile_doctor',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_specialization', to='doctor.specialization', verbose_name='التخصص'),
        ),
    ]
