# Generated by Django 3.2 on 2023-06-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_auto_20230624_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_doctor',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='الوصف'),
        ),
    ]
