# Generated by Django 3.2 on 2023-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_profile_doctor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_doctor',
            name='title',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='الوصف'),
        ),
    ]
