# Generated by Django 5.1.4 on 2025-05-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_alter_profile_doctor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'انثي')], max_length=10, null=True, verbose_name='الجنس'),
        ),
    ]
