# Generated by Django 5.1.4 on 2025-05-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_alter_profile_doctor_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'التخصص', 'verbose_name_plural': 'التخصصات'},
        ),
        migrations.AddField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='spec',
            field=models.CharField(max_length=200, unique=True, verbose_name='التخصص'),
        ),
    ]
